.TH UGIDD 8 "11 August 1997"
.SH NAME
ugidd \- uid/gid mapping daemons
.SH SYNOPSIS
.ad l
.B /usr/sbin/rpc.ugidd
.B "[\ \-P\ port\ ]"
.ad b
.\".LP
.\"or from SunOS inetd(8):
.\".B rpc udp /usr/etc/rpc.ugidd 545580417 1
.fi
.SH DESCRIPTION
.IX  "uid/gid mapping daemons"  "ugidd daemon"  ""  "\fLugidd\fP daemon"
.I ugidd
starts a
daemon that handles rpc requests to map uid/gids to string names and vice versa.
It is called by the \fInfsd\fP(8) server when the client and server do
not share the same passwd file.
.P
This version allows you to restrict access to the server through the
\fIhosts_access\fP(5) files when compiled with the -DHOSTS_ACCESS option.
Otherwise, \fIugidd\fP could be used by anyone in the Internet to obtain
a list of all valid usernames on the client machine. For instance, to 
restrict access to hosts on your class C IP network, you could add the 
following lines to \fIhosts.allow\fP and \fIhosts.deny\fP:
.PP
.nf
.I "# /etc/hosts.allow
.I "rpc.ugidd:     192.168.1.
.I "# /etc/hosts.deny
.I "rpc.ugidd:     ALL
.fi
.SH OPTIONS
.TP
.BR "\-P portnum" " or " "\-\-port portnum"
Makes
.I ugidd
listen on port
.B portnum
instead of some random port. By default,
.I ugidd
will listen on some arbitrary port number below 1024.
.SH "SEE ALSO"
exports(5), inetd(8), hosts_access(5)
.SH BUGS
The rpc program number is legal in that it lies in the 0x20000000
to 0x3fffffff ``Defined by user'' range, but is completely arbitrary.
