/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>
#include <rpc/xdr.h>

#include "ugid.h"
#include <rpc/rpc.h>

bool_t
xdr_ugname(XDR *xdrs, ugname *objp)
{

	 register long *buf=buf;

	 if (!xdr_string(xdrs, objp, MAXUGLEN)) {
		 return (FALSE);
	 }
	return (TRUE);
}
