/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UGID_H_RPCGEN
#define _UGID_H_RPCGEN

#include <rpc/rpc.h>

#include <rpc/rpc.h>
#define MAXUGLEN 64
#define NOBODY -2
#define WILDCARD -1

typedef char *ugname;
#ifdef __cplusplus 
extern "C" bool_t xdr_ugname(XDR *, ugname*);
#elif __STDC__ 
extern  bool_t xdr_ugname(XDR *, ugname*);
#else /* Old Style C */ 
bool_t xdr_ugname();
#endif /* Old Style C */ 


#define UGIDPROG ((u_long)0x2084e581)
#define UGIDVERS ((u_long)1)

#ifdef __cplusplus
#define AUTHENTICATE ((u_long)1)
extern "C" int * authenticate_1(int *, CLIENT *);
extern "C" int * authenticate_1_svc(int *, struct svc_req *);
#define NAME_UID ((u_long)2)
extern "C" int * name_uid_1(ugname *, CLIENT *);
extern "C" int * name_uid_1_svc(ugname *, struct svc_req *);
#define GROUP_GID ((u_long)3)
extern "C" int * group_gid_1(ugname *, CLIENT *);
extern "C" int * group_gid_1_svc(ugname *, struct svc_req *);
#define UID_NAME ((u_long)4)
extern "C" ugname * uid_name_1(int *, CLIENT *);
extern "C" ugname * uid_name_1_svc(int *, struct svc_req *);
#define GID_GROUP ((u_long)5)
extern "C" ugname * gid_group_1(int *, CLIENT *);
extern "C" ugname * gid_group_1_svc(int *, struct svc_req *);

#elif __STDC__
#define AUTHENTICATE ((u_long)1)
extern  int * authenticate_1(int *, CLIENT *);
extern  int * authenticate_1_svc(int *, struct svc_req *);
#define NAME_UID ((u_long)2)
extern  int * name_uid_1(ugname *, CLIENT *);
extern  int * name_uid_1_svc(ugname *, struct svc_req *);
#define GROUP_GID ((u_long)3)
extern  int * group_gid_1(ugname *, CLIENT *);
extern  int * group_gid_1_svc(ugname *, struct svc_req *);
#define UID_NAME ((u_long)4)
extern  ugname * uid_name_1(int *, CLIENT *);
extern  ugname * uid_name_1_svc(int *, struct svc_req *);
#define GID_GROUP ((u_long)5)
extern  ugname * gid_group_1(int *, CLIENT *);
extern  ugname * gid_group_1_svc(int *, struct svc_req *);

#else /* Old Style C */ 
#define AUTHENTICATE ((u_long)1)
extern  int * authenticate_1();
extern  int * authenticate_1_svc();
#define NAME_UID ((u_long)2)
extern  int * name_uid_1();
extern  int * name_uid_1_svc();
#define GROUP_GID ((u_long)3)
extern  int * group_gid_1();
extern  int * group_gid_1_svc();
#define UID_NAME ((u_long)4)
extern  ugname * uid_name_1();
extern  ugname * uid_name_1_svc();
#define GID_GROUP ((u_long)5)
extern  ugname * gid_group_1();
extern  ugname * gid_group_1_svc();
#endif /* Old Style C */ 

#endif /* !_UGID_H_RPCGEN */
